name: Update Playwright Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --update-snapshots

      - name: Commit and push changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Playwright snapshots"
          branch: update/playwright-snapshots
          title: "Update Playwright snapshots"
